apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: foodcalorie
  name: foodcalorie
  namespace: fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodcalorie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foodcalorie
    spec:
      containers:
      - image: gw01.bd.com:5000/fitness/foodcalorie:0.1
        name: foodcalorie
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: foodcalorie
    release: fitness
  name: foodcalorie
  namespace: fitness
spec:
  ports:
  - name: http-svc
    nodePort: 32672
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: foodcalorie
  type: NodePort
status:
  loadBalancer: {}
