info:
  app:
    name: foodcalorie
    version: 1.0.0-SNAPSHOT
    description:  foodcalorie

endpoints:
  shutdown:
    enabled: true
    sensitive: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: metrics,health,prometheus
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.byung8.foodcalorie.mapper
  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true
spring:
  profiles:
    active: prod
---
spring:
  profiles: prod
  pid:
    file: /data/foodcalorie/run/foodcalorie.pid
  datasource:
    url: jdbc:mysql://10.10.50.110:3306/fitness?useUnicode=yes&characterEncoding=UTF-8
    username: byung8
    password: 1q2w3e4r5t
    driverClassName: com.mysql.jdbc.Driver
logging:
  config: classpath:logback-prod.xml
log:
  file:
    path: "/data/foodcalorie/logs"
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
---
spring:
  profiles: local
  pid:
    file: D://dev/work/foodcalorie/run/foodcalorie.pid
  datasource:
    url: jdbc:mysql://192.168.0.2:13306/fitness
    username: byung8
    password: 1q2w3e4r5t
    driverClassName: com.mysql.jdbc.Driver
logging:
  config: classpath:logback-local.xml
log:
  file:
    path: "D://dev/work/foodcalorie/logs"
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
